config/routes.rb
Rails.application.routes.draw do
  # root 'main#index'
  root 'tasks#index'

  match 'about', to: "main#about", via: :get
  match 'hello', to: "main#hello", via: :get

  get 'main/index'

  resources :categories do
    member do
      get :delete
    end
  end
  resources :tasks do
    member do
      get :delete
    end
  end

  # get 'main/index'
  # get 'main/hello'
  # get 'tasks/index'
  # get 'tasks/new'
  # get 'tasks/edit'
  # get 'tasks/show'
  # get 'tasks/delete'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # get 'categories/index'
  # get 'categories/show'
  # get 'categories/new'
  # get 'categories/edit'
  # get 'categories/delete'
  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord

end

app/models/task.rb
class Task < ApplicationRecord

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

  def index
  end

  def show
  end

  def new
  end

  def create
  end

  def edit
  end

  def update
  end

  def delete
  end

  def destroy
  end

end

app/controllers/main_controller.rb
class MainController < ApplicationController

  def index
    # render('index')
  end

  def about
    @created_by = "Kevin"
    @id = params['id']
    @page = params[:page]
    # render('about')
  end

  def hello
    redirect_to(action: 'index')
  end

end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController

  def index
    @tasks = Task.order(:position)
  end

  def show
    @task = Task.find(params[:id])
    flash[:notice] = 'Book was successfully viewed.'

  end

  def new
    @count = Task.count
    @task = Task.new(position: @count + 1)
  end

  def create
    @task = Task.new(task_params)
    if @task.save
      flash[:notice] = 'Book was successfully created.'
      redirect_to tasks_path
    else
      # The 'new' action is NOT being called here
      # Assign any instance variables needed
      # @count = Task.count
      render('new')
    end
  end

  def edit
    @task = Task.find(params[:id])
    flash[:notice] = 'Book was successfully edited.'
    if @task.changed?
      flash[:notice] = 'Book was successfully created.'
    end

  end

  def update
    @task = Task.find(params[:id])
    if @task.update(task_params)
      flash[:notice] = 'Book was successfully updated.'
      redirect_to task_path(@task)
    else
      render('edit')
    end
  end

  def delete
    @task = Task.find(params[:id])
  end

  def destroy
    @task = Task.find(params[:id])
    @task.destroy
    flash[:notice] = 'Book was successfully destroyed.'

    redirect_to tasks_path
  end

  private

  def task_params
    params.require(:task).permit(
      :name,
      :position,
      :completed,
      :price,
      :description
    )
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/categories/delete.html.erb
<h1>Categories#delete</h1>
<p>Find me in app/views/categories/delete.html.erb</p>

app/views/categories/edit.html.erb
<h1>Categories#edit</h1>
<p>Find me in app/views/categories/edit.html.erb</p>

app/views/categories/index.html.erb
<h1>Categories#index</h1>
<p>Find me in app/views/categories/index.html.erb</p>

app/views/categories/new.html.erb
<h1>Categories#new</h1>
<p>Find me in app/views/categories/new.html.erb</p>

app/views/categories/show.html.erb
<h1>Categories#show</h1>
<p>Find me in app/views/categories/show.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TaskManager</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/main/about.html.erb
<h2>About</h2>

<p>Description of the Task Manager.</p>
<p>Created by <%= @created_by %></p>

ID: <%= @id %><br />
Page: <%= @page %><br />

app/views/main/index.html.erb
<h1>Task Manager</h1>
<p>This is an application for managing a to do list.</p>

<%= link_to('Categories', categories_path) %><br />
<%= link_to('Tasks', tasks_path(page: 0)) %><br />

<%= link_to('About', {action: 'about', page: 5, id: 20}) %><br />

app/views/tasks/_form.html.erb
<table summary="Task form fields">
  <tr>
    <th>Book</th>
    <td><%= f.text_field(:name) %></td>
  </tr>
  <%
=begin%>
 <tr>
    <th>Author</th>
    <td><%= f.text_field(:position) %></td>
  </tr> 
<%
=end%>
  <tr>
    <th>Price ($)</th>
    <td><%= f.text_field :price, step: '0.01' %></td>
  </tr>

 <%
=begin%>
 <tr>
    <th>Price</th>
    <td><%= f.check_box(:completed) %></td>
  </tr> 

  <tr> 
<%
=end%>
    <th>Author</th>
    <td><%= f.text_area(:description) %></td>
  </tr>
</table>

app/views/tasks/delete.html.erb
<%= link_to("Back to Books", tasks_path, class: 'back-link') %>

<div class="tasks delete">
  <h2>Delete Book</h2>

  <%= form_for(@task, method: 'delete') do |f| %>
    <% # url: task_path(@task), method: 'delete' %>

    <p>Are you sure you want to permanently delete this book?</p>
    <p><%= @task.name %></p>

    <div class="form-buttons">
      <%= f.submit("Delete Book") %>
    </div>

  <% end %>
</div>

app/views/tasks/edit.html.erb
<%= link_to("Back to Books", tasks_path, :class => 'back-link') %>

<div class="tasks edit">
  <h2>Edit Book</h2>

  <%= form_for(@task) do |f| %>
    <% # url: task_path(@task), method: 'patch' %>

    <%= render(partial: 'form', locals: {f: f}) %>

    <div class="form-buttons">
      <%= f.submit("Update Book") %>
    </div>

  <% end %>
</div>

app/views/tasks/index.html.erb
<%
=begin%>
 <%= link_to('Back to Homepage', {controller: 'main', action: 'index'}) %><br /> 
<%
=end%>

<div class="tasks index">
  <h2>Books</h2>

  <%= link_to("Add New Book", new_task_path, class: 'action new') %>

  <table class="listing" summary="Task list" style="width: 100%;">
    <tr class="header">
      <th>#</th>
      <%
=begin%>
 <th>Book(Task)</th>
      <th>Author(Completed)</th>
      <th>Price(Category)</th>
      <th>Published Date(Actions)</th> 
<%
=end%>
      <th>Book</th>
      <th>Author</th>
      <th>Price</th>
      <th>Published Date</th>
    </tr>
    <% @tasks.each do |task| %>
    <tr>
      <td><%= task.position %></td>
      <td><%= task.name %></td>
      <td><%= task.description %></td>
      <td><%= task.price %></td>


      <td><%= task.created_at %></td>


 <%
=begin%>
 <td><%= task.category %></td>  
<%
=end%>

      <td class="actions">
        <%= link_to("Show", task_path(task), class: 'action show') %>
        <%= link_to("Edit", edit_task_path(task), class: 'action edit') %>
        <%= link_to("Delete", delete_task_path(task), class: 'action delete') %>
      </td>
    </tr>
    <% end %>
  </table>

  <h3> Flash Messages show up here </h3>
  <% flash.each do |type, message| %>
    <div class="<%= type %>">
      <%= message %>
    </div>
  <% end %>
</div>

app/views/tasks/new.html.erb
<%= link_to("Back to Books", tasks_path, :class => 'back-link') %>

<div class="tasks new">
  <h2>Create Book</h2>

  <%= form_for(@task) do |f| %>
    <% # url: tasks_path, method: 'post' %>

    <%= render(partial: 'form', locals: {f: f}) %>

    <div class="form-buttons">
      <%= f.submit("Create Book") %>
    </div>

  <% end %>
</div>

app/views/tasks/show.html.erb
<%= link_to("Back to Books", tasks_path, class: 'back-link') %>

<div class="tasks show">
  <h2>Show Book</h2>

  <div class="actions">
    <%= link_to('Edit', edit_task_path(@task)) %>
    <%= link_to('Delete', delete_task_path(@task)) %>
  </div>

  <table summary="Task detail view">
    <tr>
      <th>Name</th>
      <td><%= @task.name %></td>
    </tr>
    <tr>
      <th>Position</th>
      <td><%= @task.position %></td>
    </tr>
    <tr>
      <th>Price ($)</th>
      <td><%=@task.price %></td>
    </tr>
    <tr>
      <th>Description</th>
      <td><%= @task.description %></td>
    </tr>
    
    <tr>
      <th>Created</th>
      <td><%= @task.created_at %></td>
    </tr>
    <tr>
      <th>Updated</th>
      <td><%= @task.updated_at %></td>
    </tr>
  </table>

</div>